### ISSUE TITLE
NODE_ENV environment variable is overwritten by piral-cli

### ISSUE THREAD

**Issue by lamson-dev** [FlorianRappl/piral-cli-dotenv#3]
We have a `.env.staging` file with content:

```
NODE_ENV=staging
```

We discovered that the `NODE_ENV` value is overwritten to "production" by `piral-cli` during `piral build --env .env.staging`.

This behavior is unexpected for us. Is that by design or a bug? If by design, what are the "reserved" env variables that we shouldn't use?

**Comment by FlorianRappl** [comment]
Not sure if its applied at all to be honest. This plugin only works with `piral-cli-parcel`. It may work with Webpack in combination with, e.g., `EnvironmentPlugin` and `Object.keys(process.env)`.

While you can specify any value for `NODE_ENV` my recommendation would be to leave this at `production` or `development`. This is, after all, the NODE ENV, not your environment. Many libraries use this value to decide if they should come in optimized or non optimized forms.

**Comment by lamson-dev** [comment]
@FlorianRappl yes this (unexpectedly?) works with piral-cli-webpack . I agree with you on the usage of NODE_ENV there.

**Comment by FlorianRappl** [comment]
I've added an FAQ entry for this to the README. Thanks a lot!
