### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by danbockapps** [FlorianRappl/piral-cli-dotenv#5]
I'm trying to use piral-cli-dotenv in a Piral app. I put my variables in `.env.development` and run `piral debug --env development`. In my app, I try `console.log(process.env.MY_VAR)` but it's undefined. Is there a step I'm missing?

**Comment by FlorianRappl** [comment]
What bundler are you using? I think this plugin only works with Parcel.

**Comment by danbockapps** [comment]
I'm using piral-cli-webpack. Is there a recommended way to use environment variables with webpack?

**Comment by FlorianRappl** [comment]
A combination of [EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/) and plain [dotenv](https://www.npmjs.com/package/dotenv) could just work fine.

Best case is that I find a reliable way of supporting all / multiple bundlers here.

**Comment by FlorianRappl** [comment]
On second thoughts according to #3 it also works with Webpack. Maybe there is some other issue?

What exactly are you trying to do and how are you calling it (I assume you call, e.g., `piral debug --env`, right? - from the OP everything looks fine)? Thanks @danbockapps 

What version of the `piral-cli` and the `piral-cli-webpack` packages are you using?

**Comment by danbockapps** [comment]
I have version 0.13.0 of both.

**Comment by danbockapps** [comment]
I have worked around this by uninstalling piral-cli-dotenv and creating a webpack.config.js file in the root of my piral project:

```
const path = require('path');
const webpack = require('webpack');
const dotenv = require('dotenv').config({
  path: path.join(__dirname, '.env.development'), // TODO also handle prod
});

module.exports = config => ({
  ...config,
  plugins: config.plugins.concat(
    new webpack.DefinePlugin({ 'process.env': JSON.stringify(dotenv.parsed) }),
  ),
});
```
Now I can refer to `process.env` in my TypeScript code to access the values from .env.development.

**Comment by FlorianRappl** [comment]
Actually, I've updated the plugin. It would have worked with  `--env .env.development`, but after the update (version is 0.2.0) it should also work as expected. Sorry for the inconvenience!
