### ISSUE TITLE
Overriding variables from Pilet

### ISSUE THREAD

**Issue by prepfarm** [FlorianRappl/piral-cli-dotenv#6]
If I have auth client inside Piral instance with `AUTH_CLIENT_ID` variable that's coming from `.env`, how can I override that variable when running Pilet? I can run `piral build --env` to include some default variables, but I want to override some so I can test locally without having to use emulator and do changes to `.env` there and then use that inside Pilet.

If I specify same name inside .env in Pilet (and use `pilet debug --env`, console.log from Piral instance is showing its own defined variable. Not defining one in Piral instance gives process not found error.

Thanks

**Comment by FlorianRappl** [comment]
I think there is a misunderstanding:

1. Environment variables are constructs that live on your machine / some server
2. The application when running is a SPA - therefore no environment variables are taken there
3. To use environment variables the `process.env....` references are **replaced** at **build-time** with their *current* values
4. If some value (e.g., `process.env.AUTH_CLIENT_ID`) was replaced at build-time in your shell then the env reference does not exist any more - it is now a hard-coded value

Therefore, the whole problem has nothing to do with Piral / or .env files, but rather with how you structure your application. If you want to override then maybe use `localStorage` or `sessionStorage` or some object on `window` and fall back to the hardcoded value obtained at build-time by replacement.

Hope that helps.
